services:
  db:
    image: postgres:16
    container_name: pg-ml
    environment:
      POSTGRES_USER: smail
      POSTGRES_PASSWORD: smail
      POSTGRES_DB: mldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./imports:/imports
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smail -d mldb"]
      interval: 5s
      timeout: 3s
      retries: 20
  

volumes:
  pgdata:
